name: Build and Deploy
concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [main]
    paths: [".github/**"]
  workflow_dispatch:
  repository_dispatch:
    types: [build-and-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: maciej-irl/wate
          lfs: true

      - name: Install and Build
        run: |
          echo '{"wordy": true}' > src/config.json
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
